#!/bin/sh
pkg install -y keylaunch
cp /usr/local/share/examples/keylaunch/keylaunch.rc /root/.keylaunchrc
find /usr/home -type d -maxdepth 1 | grep "/usr/home/.*" |grep -v -e '^$' | xargs cp /root/.keylaunchrc
find /usr/home -maxdepth 1 -type d | cut -d '/' -f 4 | grep -v -e '^$' | grep -v 'lost+found' | xargs -I {} chown {}:{} /usr/home/{}/.keylaunchrc
echo "#!/bin/sh" > /root/.xsession
echo "exec /usr/local/bin/keylaunch &" >> /root/.xsession
