#!/bin/sh
pkg install -y larswm
echo "exec /usr/local/bin/larswm" >> /root/.xsession
cp /usr/local/share/doc/larswm/sample.larswmrc /root/.larswmrc
find /usr/home -type d -maxdepth 1 | grep "/usr/home/.*" |grep -v -e '^$' | xargs cp /root/.larswmrc
find /usr/home -maxdepth 1 -type d | cut -d '/' -f 4 | grep -v -e '^$' | grep -v 'lost+found' | xargs -I {} chown {}:{} /usr/home/{}/.larswmrc
sh $(dirname "$0")/xdm
sh $(dirname "$0")/keylaunch
